### ISSUE TITLE
DerivationCodeSequence not populated correctly

### ISSUE THREAD

**Issue by fedorov** [pieper/dcmjs#5]
CodeMeaning can't be correct

![image](https://user-images.githubusercontent.com/313942/27921522-0c2cd15a-6246-11e7-93c2-b4e9e67ad50b.png)

**Comment by pieper** [comment]
I see - yes, the CodeMeaning should be string "Segmentation" but this is being auto-converted back to the corresponding SOPClassUID of the same name.  Will need to do something dependent on the VR to decide if a UID should be converted.

**Comment by fedorov** [comment]
Steve, this code is unrelated to Segmentation SOPClassUID

**Comment by pieper** [comment]
Yes, that's why I said it's incorrectly being autoconverted into a UID when it should be just the string "Segmentation".

**Comment by fedorov** [comment]
I meant to say I am confused why there is a decision between converting anything into a UID at all present here. The item in question is part of a code sequence, which describes the purpose of referencing a given instance. Code 113076 is from a DCM dictionary, and its meaning is "Segmentation". I don't understand why VR should have any role in any decision making here.

**Comment by pieper** [comment]
The idea was to behave like dcmdump, where if there is a recognized UID it
is replaced by the corresponding human readable name of the UID (in their
case with an equals sign in front of it).  Then dump2dcm recognizes this
and converts back to a UID string of numbers.  My first (current)
implementation didn't account for the case where the value of a tag could
have the same string as a UID name, but obviously that wasn't valid.  I've
started making [notes on the wiki page](
https://github.com/pieper/dcmjs/wiki/NDD-Format) about the conversion.

**Comment by fedorov** [comment]
> if there is a recognized UID it is replaced by the corresponding human readable name of the UID

Yes, I understand, but I am not sure going the other direction (name to UID) is a good idea. What motivated you to add this feature?

**Comment by pieper** [comment]
Mainly just readability.  I wanted to avoid having any hex or uid strings in the code.  But as I said I'm backing off that feature and instead I plan to just have programmers use the dictionary directly to map names to UID strings.
